[project]
name = "fast-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Weskley Moreira", email = "weskleymdev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "httpie>=3.2.4",
    "httpx2>=2.13.1",
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.1.1",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
fast-zero = "fast_zero:main"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = "double"

[tool.taskipy.tasks]
run = 'uvicorn fast_zero.app:app --reload'

pre_test = 'task lint'
test = {cmd = 'pytest --cov=fast_zero -vv', help = 'Run tests with coverage'}
post_test = 'coverage html'

lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff format .'

migrations = { cmd = "alembic revision --autogenerate -m", help = "Create a new migration" }

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
    "taskipy>=1.14.1",
]
